set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# hjkl 切换 
set -g @plugin 'christoomey/vim-tmux-navigator'
# 将状态栏放在顶部
set -g status-position top
# 窗口名称居中显示
set -g status-justify centre
#
# # 主题
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g @catppuccin_flavor "latte"
set -g @catppuccin_window_status_style "rounded"

# 关闭后编号连续
set -g renumber-window on
# 开启鼠标支持 
set -g mouse on

# 设置prefix快捷键
unbind C-b
set -g prefix C-s

# 强制覆盖状态栏样式（透明背景）
set -g status-style bg=default,fg='#4c4f69'
set -g window-status-style bg=default,fg='#9ca0b0'
set -g window-status-current-style bg=default,fg='#dc8add'

run '~/.tmux/plugins/tpm/tpm'


# ╭──────────────────────────────────────────────────────────╮
# │                           Pane                           │
# ╰──────────────────────────────────────────────────────────╯
bind i run-shell " \
if [ $(( \$(tmux display -p '8*#{pane_width}-20*#{pane_height}') )) -lt 0 ]; then \
  tmux splitw -v -c '#{pane_current_path}'; \
else \
  tmux splitw -h -c '#{pane_current_path}'; \
fi"
